---
- hosts: all
  gather_facts: false
  task:
  - vsphere_guest:
        vcenter_hostname: vcenter.mydomain.local
        username: myuser
        password: mypass
        guest: newvm001
        state: powered_on
        vm_extra_config:
            vcpu.hotadd: yes
            mem.hotadd:  yes
            notes: This is a test VM
            folder: MyFolder
        vm_disk:
            disk1:
            size_gb: 10
            type: thin
            datastore: storage001
            folder: production/customerA/lamp
        vm_nic:
            nic1:
            type: vmxnet3
            network: VM Network
            network_type: standard
        vm_hardware:
            memory_mb: 16000
            num_cpus: 4
            osid: centos64Guest
            scsi: paravirtual
        vm_cdrom:
            type: "iso"
            iso_path: "DatastoreName/cd-image.iso"
        esxi:
            datacenter: 192.168.1.11
            hostname: localhost.localdomain
