---
- name: VM From Template
  hosts: vmcreate
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: 192.168.1.11
    datastore: xvdstrlun01
    network: "VM Network"
  tasks:
  - name: Create VM
    vmsphere_guest:
      validate_certs: False
      hostname: "{{ vcenter_hostname }}"
      username: root
      password: Xvale123
      name: testvm01
      vm_disk:
        size_gb: 10 
        type: thin
        datastore: xvdstrlun01
      vm_nic:
        type: vmxnet3
        network: "{{ network }}"
        network_type: standard
      vm_hardware:
        memory_mb: 16000
        num_cpus: 4
        osid: centos64Guest
        scsi: paravirtual
      vm_cdrom:
        type: "iso"
        iso_path: "[xvdstrlun01] ISO/rhel-server-7.4-x86_64-dvd.iso"
